import { Card } from '@primereact/ui/card';
import { Button } from '@primereact/ui/button';
import { ProgressSpinner } from '@primereact/ui/progressspinner';
import { useEffect, useState } from 'react';
import { Link, Navigate, useNavigate } from 'react-router-dom';
import { useAuth } from '../auth/AuthProvider';

export function LandingPage() { return <section className="landing"><h1>eGuEducation</h1><p>Platformă digitală pentru administrarea instituțiilor de învățământ.</p><p>Autentificați-vă pentru a accesa modulele pentru care aveți drepturi.</p></section>; }
const Panel = ({ title, children }: { title: string; children: React.ReactNode }) => <Card.Root><Card.Body><Card.Title><h1>{title}</h1></Card.Title><Card.Content>{children}</Card.Content></Card.Body></Card.Root>;
export function RegistrationPage() { const { login } = useAuth(); return <main className="flex min-h-screen items-center justify-center p-6"><Panel title="Acces eGuEducation"><div className="flex max-w-xl flex-col gap-4"><p>Conturile sunt create și asociate instituției de un administrator autorizat. Auto-înregistrarea publică nu este disponibilă, pentru a proteja datele școlare și separarea dintre instituții.</p><p>Dacă aveți deja cont, continuați cu autentificarea. Pentru un cont nou, contactați administratorul instituției.</p><div className="flex flex-wrap gap-2"><Button onClick={() => void login()}>Autentificare</Button><Button as={Link} to="/" variant="outlined">Prima pagină</Button></div></div></Panel></main>; }
export function WorkspacePage({ title, description }: { title: string; description: string }) { return <Panel title={title}><p>{description}</p></Panel>; }
export function ProfilePage() { const { user } = useAuth(); return <Panel title="Profil utilizator"><dl><dt>Nume</dt><dd>{user?.name}</dd><dt>E-mail</dt><dd>{user?.email ?? '—'}</dd></dl></Panel>; }
const Spinner = () => <ProgressSpinner.Root><ProgressSpinner.Range><ProgressSpinner.Track /><ProgressSpinner.Value /></ProgressSpinner.Range></ProgressSpinner.Root>;
export function CallbackPage() { const { complete } = useAuth(); const navigate = useNavigate(); const [error, setError] = useState<string>(); useEffect(() => { void complete().then((returnTo) => navigate(returnTo, { replace: true })).catch((reason: unknown) => setError(reason instanceof Error ? reason.message : 'Autentificarea nu a putut fi finalizată.')); }, [complete, navigate]); if (error) return <Panel title="Autentificare nereușită"><p role="alert">{error}</p><Button as={Link} to="/" variant="outlined">Înapoi la prima pagină</Button></Panel>; return <div className="flex justify-center p-8"><Spinner /></div>; }
export function LogoutCallbackPage() { const { completeLogout } = useAuth(); const navigate = useNavigate(); const [error, setError] = useState<string>(); useEffect(() => { try { completeLogout(); navigate('/', { replace: true }); } catch (reason) { setError(reason instanceof Error ? reason.message : 'Deconectarea OIDC nu a putut fi validată.'); } }, [completeLogout, navigate]); if (error) return <Panel title="Deconectare nereușită"><p role="alert">{error}</p><Button as={Link} to="/" variant="outlined">Înapoi la prima pagină</Button></Panel>; return <div className="flex justify-center p-8"><Spinner /></div>; }
export function RequirePermission({ permission, module, children }: { permission: string; module?: string; children: React.ReactNode }) { const { ready, has, session } = useAuth(); if (!ready) return <div className="flex justify-center p-8"><Spinner /></div>; const moduleActive = !module || Boolean(session?.modules.some((item) => item.code === module && item.active)); return has(permission) && moduleActive ? <>{children}</> : <Navigate to="/" replace />; }
export function RequireAuthenticated({ children }: { children: React.ReactNode }) { const { ready, user } = useAuth(); if (!ready) return <div className="flex justify-center p-8"><Spinner /></div>; return user ? <>{children}</> : <Navigate to="/" replace />; }
