import { useCallback, useEffect, useRef, useState, type ChangeEvent, type FormEvent } from "react";
import { Button } from "@primereact/ui/button";
import { DataTable } from "@primereact/ui/datatable";
import { Dialog } from "@primereact/ui/dialog";
import { InputText } from "@primereact/ui/inputtext";
import { Message } from "@primereact/ui/message";
import { ProgressSpinner } from "@primereact/ui/progressspinner";
import { Select } from "@primereact/ui/select";
import type { SelectValueChangeEvent } from "primereact/select";
import { Tag } from "@primereact/ui/tag";
import { Textarea } from "@primereact/ui/textarea";
import { Download, Eye, Plus, Refresh } from "@primeicons/react";
import { sourceKinds, type RegulatorySource, type RegulatorySourcesApi, type RegulatorySourcesQuery, type RegulatorySourceStatus, type RegisterRegulatorySource, type SourceKind } from "./api";

type Capability = { read: boolean; manage: boolean; verify: boolean; activate: boolean };
type FormState = { citation: string; publisher_url: string; issuer: string; source_kind: SourceKind; applicable_from: string; applicable_until: string };
const defaultForm = (): FormState => ({ citation: "", publisher_url: "", issuer: "", source_kind: "law", applicable_from: "", applicable_until: "" });
const statusOptions: Array<{ label: string; value: RegulatorySourceStatus | "" }> = [{ label: "Toate stările", value: "" }, { label: "Ciornă", value: "draft" }, { label: "Verificată", value: "verified" }, { label: "Activă", value: "active" }];
const kindOptions = [{ label: "Toate tipurile", value: "" }, ...sourceKinds.map(value => ({ label: kindLabel(value), value }))];

export function RegulatorySourcesWorkspace({ api, capabilities, actorSubject }: { api: RegulatorySourcesApi; capabilities: Capability; actorSubject?: string }) {
  const [query, setQuery] = useState<RegulatorySourcesQuery>({ page: 1, pageSize: 20, sort: "updated_at", direction: "desc" });
  const [page, setPage] = useState({ items: [] as RegulatorySource[], total: 0, page: 1, pageSize: 20 });
  const [loading, setLoading] = useState(true); const [saving, setSaving] = useState(false); const [error, setError] = useState<string>();
  const [registerOpen, setRegisterOpen] = useState(false); const [activateTarget, setActivateTarget] = useState<RegulatorySource>(); const [form, setForm] = useState(defaultForm); const [assessment, setAssessment] = useState(""); const [evidenceID, setEvidenceID] = useState("");
  const sequence = useRef(0);
  const load = useCallback(async () => { const current = ++sequence.current; setLoading(true); setError(undefined); try { const result = await api.list(query); if (current === sequence.current) setPage(result); } catch { if (current === sequence.current) setError("Registrul surselor nu a putut fi încărcat."); } finally { if (current === sequence.current) setLoading(false); } }, [api, query]);
  useEffect(() => { void load(); return () => { sequence.current += 1; }; }, [load]);
  const mutate = async (operation: () => Promise<unknown>, failure: string) => { setSaving(true); setError(undefined); try { await operation(); await load(); } catch { setError(failure); } finally { setSaving(false); } };
  const register = (event: FormEvent) => { event.preventDefault(); const input = normalizeForm(form); if (!input) { setError("Completați citarea, emitentul și o adresă web validă."); return; } void mutate(async () => { await api.register(input); setRegisterOpen(false); setForm(defaultForm()); }, "Înregistrarea sursei a fost refuzată."); };
  const verify = (source: RegulatorySource) => void mutate(() => api.verify(source.id, source.expected_version), "Verificarea a fost refuzată; reîncărcați sursa și încercați din nou.");
  const activate = (event: FormEvent) => { event.preventDefault(); if (!activateTarget || !evidenceID.trim() || !assessment.trim()) { setError("Indicați evidența și evaluarea de aplicabilitate înainte de activare."); return; } void mutate(async () => { await api.activate(activateTarget.id, { expected_version: activateTarget.expected_version, evidence_id: evidenceID.trim(), assessment: assessment.trim() }); setActivateTarget(undefined); setEvidenceID(""); setAssessment(""); }, "Activarea a fost refuzată; reîncărcați sursa și încercați din nou."); };
  const download = async (source: RegulatorySource, view: boolean) => { if (!source.latest_evidence_id) return; try { const blob = await api.evidence(source.id, source.latest_evidence_id); const url = URL.createObjectURL(blob); if (view) window.open(url, "_blank", "noopener,noreferrer"); else { const anchor = document.createElement("a"); anchor.href = url; anchor.download = `evidenta-${source.id}`; anchor.click(); } window.setTimeout(() => URL.revokeObjectURL(url), 1000); } catch { setError("Evidența nu a putut fi deschisă."); } };
  const canVerify = (source: RegulatorySource) => capabilities.verify && source.status === "draft";
  const canActivate = (source: RegulatorySource) => capabilities.activate && Boolean(actorSubject) && source.status === "verified" && source.latest_evidence_id !== null && source.created_by_subject !== actorSubject;
  const openActivation = (source: RegulatorySource) => { setActivateTarget(source); setEvidenceID(source.latest_evidence_id ?? ""); setAssessment(""); };
  const changeFilter = (patch: Partial<RegulatorySourcesQuery>) => setQuery(value => ({ ...value, ...patch, page: 1 }));
  const sort = (field: RegulatorySourcesQuery["sort"]) => setQuery(value => ({ ...value, page: 1, sort: field, direction: value.sort === field && value.direction === "asc" ? "desc" : "asc" }));
  const last = Math.max(1, Math.ceil(page.total / page.pageSize));
  return <section aria-label="Surse de reglementare" className="mt-4 flex flex-col gap-3">
    {error && <Message.Root severity="error"><Message.Content><Message.Text>{error}</Message.Text></Message.Content></Message.Root>}
    <div className="max-h-[min(58dvh,34rem)] overflow-auto rounded-border border border-surface">
      {loading ? <div className="flex justify-center p-8" role="status" aria-label="Se încarcă sursele"><Spinner /></div> : <DataTable.Root data={page.items as unknown as Record<string, unknown>[]} dataKey="id"><DataTable.Table><DataTable.THead className="sticky top-0 z-10 bg-surface-0"><DataTable.THeadRow>
        <DataTable.THeadCell><Button size="small" variant="text" onClick={() => sort("citation")}>Citare</Button></DataTable.THeadCell><DataTable.THeadCell><Button size="small" variant="text" onClick={() => sort("source_kind")}>Tip</Button></DataTable.THeadCell><DataTable.THeadCell><Button size="small" variant="text" onClick={() => sort("status")}>Stare</Button></DataTable.THeadCell><DataTable.THeadCell><Button size="small" variant="text" onClick={() => sort("updated_at")}>Actualizată</Button></DataTable.THeadCell><DataTable.THeadCell><span>Acțiuni </span>{capabilities.manage && <Button size="small" onClick={() => setRegisterOpen(true)}><Plus />Adaugă</Button>}</DataTable.THeadCell>
      </DataTable.THeadRow><DataTable.THeadRow><DataTable.THeadCell><InputText aria-label="Filtru citare" value={query.citation ?? ""} onChange={(event: ChangeEvent<HTMLInputElement>) => changeFilter({ citation: event.target.value || undefined })} /></DataTable.THeadCell><DataTable.THeadCell><Picker ariaLabel="Filtru tip sursă" value={query.source_kind ?? ""} options={kindOptions} onChange={value => changeFilter({ source_kind: isSourceKind(value) ? value : undefined })} /></DataTable.THeadCell><DataTable.THeadCell><Picker ariaLabel="Filtru stare" value={query.status ?? ""} options={statusOptions} onChange={value => changeFilter({ status: isStatus(value) ? value : undefined })} /></DataTable.THeadCell><DataTable.THeadCell /><DataTable.THeadCell /></DataTable.THeadRow></DataTable.THead>
      <DataTable.TBody>{({ item, index }: { item: Record<string, unknown>; index: number }) => { const source = item as unknown as RegulatorySource; return <DataTable.Row key={source.id} index={index}><DataTable.Cell><a className="text-primary hover:underline" href={source.publisher_url} target="_blank" rel="noreferrer">{source.citation}</a><div className="text-sm text-color-secondary">{source.issuer}</div></DataTable.Cell><DataTable.Cell>{kindLabel(source.source_kind)}</DataTable.Cell><DataTable.Cell><Tag value={statusLabel(source.status)} severity={source.status === "active" ? "success" : source.status === "verified" ? "info" : "secondary"} /></DataTable.Cell><DataTable.Cell>{formatDate(source.updated_at)}</DataTable.Cell><DataTable.Cell><div className="flex flex-wrap gap-1">{source.latest_evidence_id && <><Button size="small" variant="text" aria-label={`Deschide evidența ${source.citation}`} onClick={() => void download(source, true)}><Eye /></Button><Button size="small" variant="text" aria-label={`Descarcă evidența ${source.citation}`} onClick={() => void download(source, false)}><Download /></Button></>}{canVerify(source) && <Button size="small" onClick={() => verify(source)} disabled={saving}>Verifică</Button>}{canActivate(source) && <Button size="small" onClick={() => openActivation(source)} disabled={saving}>Activează</Button>}</div></DataTable.Cell></DataTable.Row>; }}</DataTable.TBody></DataTable.Table></DataTable.Root>}
    </div>
    <div className="sticky bottom-0 flex flex-wrap items-center justify-between gap-2 border-t border-surface bg-surface-0 pt-2"><span>{page.total} surse</span><div className="flex items-center gap-2"><Button size="small" variant="outlined" severity="secondary" onClick={() => void load()} disabled={loading}><Refresh />Reîncarcă</Button><Button size="small" disabled={query.page <= 1 || loading} onClick={() => setQuery(value => ({ ...value, page: value.page - 1 }))}>Anterior</Button><span aria-label="Pagina curentă">{query.page} / {last}</span><Button size="small" disabled={query.page >= last || loading} onClick={() => setQuery(value => ({ ...value, page: value.page + 1 }))}>Următor</Button></div></div>
    <RegisterDialog open={registerOpen} error={registerOpen ? error : undefined} form={form} saving={saving} onClose={() => setRegisterOpen(false)} onChange={setForm} onSave={register} />
    <ActivateDialog source={activateTarget} error={activateTarget ? error : undefined} evidenceID={evidenceID} assessment={assessment} saving={saving} onClose={() => setActivateTarget(undefined)} onEvidence={setEvidenceID} onAssessment={setAssessment} onSave={activate} />
  </section>;
}

function Picker({ ariaLabel, value, options, onChange }: { ariaLabel: string; value: string; options: Array<{ label: string; value: string }>; onChange: (value: string) => void }) { return <Select.Root value={value} options={options} optionLabel="label" optionValue="value" onValueChange={(event: SelectValueChangeEvent) => onChange(String(event.value ?? ""))}><Select.Trigger aria-label={ariaLabel}><Select.Value /><Select.Indicator /></Select.Trigger><Select.Portal><Select.Positioner><Select.Popup><Select.List /></Select.Popup></Select.Positioner></Select.Portal></Select.Root>; }
function RegisterDialog({ open, error, form, saving, onClose, onChange, onSave }: { open: boolean; error?: string; form: FormState; saving: boolean; onClose: () => void; onChange: (value: FormState) => void; onSave: (event: FormEvent) => void }) { const set = (key: keyof FormState, value: string) => onChange({ ...form, [key]: value }); return <Dialog.Root open={open} onOpenChange={(event: { value?: boolean }) => { if (!event.value) onClose(); }}><Dialog.Portal><Dialog.Backdrop /><Dialog.Positioner><Dialog.Popup className="w-[min(96vw,42rem)]"><form onSubmit={onSave}><Dialog.Header><Dialog.Title>Înregistrează sursă</Dialog.Title></Dialog.Header><Dialog.Content>{error && <Message.Root severity="error"><Message.Content><Message.Text>{error}</Message.Text></Message.Content></Message.Root>}<p className="mb-3 text-sm text-color-secondary">Înregistrarea creează o ciornă; nu atestă verificarea sau aplicabilitatea juridică.</p><div className="grid gap-3 sm:grid-cols-2"><label className="flex flex-col gap-1 sm:col-span-2">Citare<InputText required value={form.citation} onChange={(event: ChangeEvent<HTMLInputElement>) => set("citation", event.target.value)} /></label><label className="flex flex-col gap-1 sm:col-span-2">URL publicare<InputText required type="url" value={form.publisher_url} onChange={(event: ChangeEvent<HTMLInputElement>) => set("publisher_url", event.target.value)} /></label><label className="flex flex-col gap-1">Emitent<InputText required value={form.issuer} onChange={(event: ChangeEvent<HTMLInputElement>) => set("issuer", event.target.value)} /></label><label className="flex flex-col gap-1">Tip sursă<Picker ariaLabel="Tip sursă" value={form.source_kind} options={sourceKinds.map(value => ({ label: kindLabel(value), value }))} onChange={value => { if (isSourceKind(value)) set("source_kind", value); }} /></label><label className="flex flex-col gap-1">Aplicabilă de la<InputText required type="date" value={form.applicable_from} onChange={(event: ChangeEvent<HTMLInputElement>) => set("applicable_from", event.target.value)} /></label><label className="flex flex-col gap-1">Aplicabilă până la<InputText type="date" value={form.applicable_until} onChange={(event: ChangeEvent<HTMLInputElement>) => set("applicable_until", event.target.value)} /></label></div></Dialog.Content><Dialog.Footer><Button type="button" variant="outlined" severity="secondary" onClick={onClose} disabled={saving}>Anulează</Button><Button type="submit" disabled={saving}>{saving ? "Se salvează…" : "Înregistrează"}</Button></Dialog.Footer></form></Dialog.Popup></Dialog.Positioner></Dialog.Portal></Dialog.Root>; }
function ActivateDialog({ source, error, evidenceID, assessment, saving, onClose, onEvidence, onAssessment, onSave }: { source?: RegulatorySource; error?: string; evidenceID: string; assessment: string; saving: boolean; onClose: () => void; onEvidence: (value: string) => void; onAssessment: (value: string) => void; onSave: (event: FormEvent) => void }) { return <Dialog.Root open={Boolean(source)} onOpenChange={(event: { value?: boolean }) => { if (!event.value) onClose(); }}><Dialog.Portal><Dialog.Backdrop /><Dialog.Positioner><Dialog.Popup className="w-[min(96vw,38rem)]"><form onSubmit={onSave}><Dialog.Header><Dialog.Title>Activează sursa</Dialog.Title></Dialog.Header><Dialog.Content>{error && <Message.Root severity="error"><Message.Content><Message.Text>{error}</Message.Text></Message.Content></Message.Root>}<p className="mb-3 text-sm text-color-secondary">Activarea atestă aplicabilitatea evaluată pentru instituție. Nu reprezintă calificarea unei semnături.</p><label className="mb-3 flex flex-col gap-1">ID evidență<InputText readOnly required value={evidenceID} /></label><label className="flex flex-col gap-1">Evaluare aplicabilitate<Textarea required value={assessment} onChange={(event: ChangeEvent<HTMLTextAreaElement>) => onAssessment(event.target.value)} /></label></Dialog.Content><Dialog.Footer><Button type="button" variant="outlined" severity="secondary" onClick={onClose} disabled={saving}>Anulează</Button><Button type="submit" disabled={saving}>{saving ? "Se activează…" : "Activează"}</Button></Dialog.Footer></form></Dialog.Popup></Dialog.Positioner></Dialog.Portal></Dialog.Root>; }
const Spinner = () => <ProgressSpinner.Root><ProgressSpinner.Range><ProgressSpinner.Track /><ProgressSpinner.Value /></ProgressSpinner.Range></ProgressSpinner.Root>;
const normalizeForm = (form: FormState): RegisterRegulatorySource | undefined => { try { new URL(form.publisher_url); } catch { return undefined; } return form.citation.trim() && form.issuer.trim() && form.applicable_from ? { citation: form.citation.trim(), publisher_url: form.publisher_url.trim(), issuer: form.issuer.trim(), source_kind: form.source_kind, applicable_from: form.applicable_from, applicable_until: form.applicable_until || null } : undefined; };
function kindLabel(value: SourceKind) { return ({ law: "Lege", government_decision: "Hotărâre de guvern", ministerial_order: "Ordin ministerial", authorization: "Autorizare", accreditation: "Acreditare", founder_decision: "Decizie fondator", contract: "Contract", other: "Altul" } as Record<SourceKind, string>)[value]; }
function statusLabel(value: RegulatorySourceStatus) { return ({ draft: "Ciornă", verified: "Verificată", active: "Activă", superseded: "Înlocuită", withdrawn: "Retrasă" } as Record<RegulatorySourceStatus, string>)[value]; }
function isSourceKind(value: string): value is SourceKind { return sourceKinds.includes(value as SourceKind); }
function isStatus(value: string): value is RegulatorySourceStatus { return ["draft", "verified", "active", "superseded", "withdrawn"].includes(value); }
function formatDate(value: string) { const date = new Date(value); return Number.isNaN(date.valueOf()) ? value : date.toLocaleDateString("ro-RO"); }
