insert into app_permissions(code, label) values
	('education.governance.meeting.close', 'Close education governance meetings'),
	('education.governance.meeting.vote', 'Cast or record governance meeting votes'),
	('education.governance.minutes.publish', 'Publish governance meeting minutes'),
	('education.governance.resolution.publish', 'Publish governance resolutions'),
	('education.portfolios.verify', 'Verify professional portfolios'),
	('education.portfolios.transfer', 'Transfer professional portfolios'),
	('education.portfolios.custody.manage', 'Manage professional portfolio custody'),
	('education.managerial.publish', 'Publish education managerial documents'),
	('education.reports.export_sensitive', 'Export sensitive education reports'),
	('education.inspect.package.read', 'Read education inspection packages')
on conflict (code) do nothing;

insert into app_role_permissions (role_code, permission_code)
select role_code, permission_code
from (values
	('super_admin', 'education.governance.meeting.close'),
	('super_admin', 'education.governance.meeting.vote'),
	('super_admin', 'education.governance.minutes.publish'),
	('super_admin', 'education.governance.resolution.publish'),
	('super_admin', 'education.portfolios.verify'),
	('super_admin', 'education.portfolios.transfer'),
	('super_admin', 'education.portfolios.custody.manage'),
	('super_admin', 'education.managerial.publish'),
	('super_admin', 'education.reports.export_sensitive'),
	('super_admin', 'education.inspect.package.read'),
	('admin', 'education.governance.meeting.close'),
	('admin', 'education.governance.meeting.vote'),
	('admin', 'education.governance.minutes.publish'),
	('admin', 'education.governance.resolution.publish'),
	('admin', 'education.portfolios.verify'),
	('admin', 'education.portfolios.transfer'),
	('admin', 'education.portfolios.custody.manage'),
	('admin', 'education.managerial.publish'),
	('admin', 'education.reports.export_sensitive'),
	('admin', 'education.inspect.package.read'),
	('director', 'education.governance.meeting.close'),
	('director', 'education.governance.meeting.vote'),
	('director', 'education.governance.minutes.publish'),
	('director', 'education.governance.resolution.publish'),
	('director', 'education.portfolios.verify'),
	('director', 'education.portfolios.transfer'),
	('director', 'education.portfolios.custody.manage'),
	('director', 'education.managerial.publish'),
	('director', 'education.reports.export_sensitive'),
	('director', 'education.inspect.package.read'),
	('secretar', 'education.governance.meeting.vote'),
	('secretar', 'education.governance.minutes.publish'),
	('secretar', 'education.governance.resolution.publish'),
	('secretar', 'education.portfolios.verify'),
	('secretar', 'education.portfolios.transfer'),
	('secretar', 'education.portfolios.custody.manage'),
	('secretar', 'education.managerial.publish'),
	('secretar', 'education.reports.export_sensitive'),
	('inspector', 'education.inspect.package.read'),
	('inspector', 'education.reports.export_sensitive'),
	('gdpr_officer', 'education.reports.export_sensitive'),
	('profesor', 'education.governance.meeting.vote')
) as mapping(role_code, permission_code)
on conflict do nothing;
