select set_config('app.is_super_admin', 'true', true);
create table school_education_contracts (
 id uuid primary key default gen_random_uuid(), tenant_code text not null, institution_id text not null, student_party_id uuid, guardian_party_id uuid, offering_id uuid, contract_number text not null, status text not null check(status in ('draft','active','suspended','terminated','archived')), starts_on date not null, ends_on date, tuition_amount numeric(16,2) check(tuition_amount is null or tuition_amount>=0), currency text not null default 'RON',
 expected_version integer not null default 1 check(expected_version>0), source_id uuid, created_by_subject text not null, created_at timestamptz not null default now(), updated_by_subject text not null, updated_at timestamptz not null default now(), unique(tenant_code,institution_id,id), unique(tenant_code,institution_id,contract_number), foreign key(tenant_code,institution_id) references app_tenants(code,institution_id) on delete restrict,
 foreign key(tenant_code,institution_id,offering_id) references school_education_offerings(tenant_code,institution_id,id) on delete restrict, foreign key(tenant_code,institution_id,student_party_id) references app_parties(tenant_code,institution_id,id) on delete restrict, foreign key(tenant_code,institution_id,guardian_party_id) references app_parties(tenant_code,institution_id,id) on delete restrict, foreign key(tenant_code,institution_id,source_id) references school_regulatory_sources(tenant_code,institution_id,id) on delete restrict, check(ends_on is null or ends_on>=starts_on)
);
create table school_quality_cycles (
 id uuid primary key default gen_random_uuid(), tenant_code text not null, institution_id text not null, code text not null, title text not null, status text not null check(status in ('planned','in_progress','complete','archived')), starts_on date not null, ends_on date, expected_version integer not null default 1 check(expected_version>0), source_id uuid not null, created_by_subject text not null, created_at timestamptz not null default now(), updated_by_subject text not null, updated_at timestamptz not null default now(), unique(tenant_code,institution_id,id), unique(tenant_code,institution_id,code), foreign key(tenant_code,institution_id) references app_tenants(code,institution_id) on delete restrict, foreign key(tenant_code,institution_id,source_id) references school_regulatory_sources(tenant_code,institution_id,id) on delete restrict, check(ends_on is null or ends_on>=starts_on)
);
create table school_network_memberships (
 id uuid primary key default gen_random_uuid(), tenant_code text not null, institution_id text not null, network_code text not null, network_name text not null, status text not null check(status in ('active','suspended','ended')), effective_from date not null, effective_to date, expected_version integer not null default 1 check(expected_version>0), source_id uuid not null, created_by_subject text not null, created_at timestamptz not null default now(), updated_by_subject text not null, updated_at timestamptz not null default now(), unique(tenant_code,institution_id,id), unique(tenant_code,institution_id,network_code,effective_from), foreign key(tenant_code,institution_id) references app_tenants(code,institution_id) on delete restrict, foreign key(tenant_code,institution_id,source_id) references school_regulatory_sources(tenant_code,institution_id,id) on delete restrict, check(effective_to is null or effective_to>=effective_from)
);
