-- Immutable input/evaluation snapshots preserve the exact legal context used by a command.
select set_config('app.is_super_admin', 'true', true);
create table school_operation_policy_inputs (
 id uuid primary key default gen_random_uuid(), tenant_code text not null, institution_id text not null, operation_code text not null, profile_id uuid not null, profile_version integer not null, offering_id uuid, location_id uuid, funding_instrument_id uuid, procurement_assessment_id uuid, context jsonb not null, checksum_sha256 text not null check(checksum_sha256 ~ '^[a-f0-9]{64}$'), created_by_subject text not null, created_at timestamptz not null default now(),
 unique(tenant_code,institution_id,id), foreign key(tenant_code,institution_id) references app_tenants(code,institution_id) on delete restrict, foreign key(tenant_code,institution_id,profile_id,profile_version) references school_institution_profiles_v2(tenant_code,institution_id,id,version) on delete restrict, foreign key(tenant_code,institution_id,offering_id) references school_education_offerings(tenant_code,institution_id,id) on delete restrict, foreign key(tenant_code,institution_id,location_id) references school_locations(tenant_code,institution_id,id) on delete restrict, foreign key(tenant_code,institution_id,funding_instrument_id) references school_funding_instruments(tenant_code,institution_id,id) on delete restrict, foreign key(tenant_code,institution_id,procurement_assessment_id) references school_procurement_applicability_assessments(tenant_code,institution_id,id) on delete restrict, check(jsonb_typeof(context)='object')
);
create table school_operation_policy_evaluations_v2 (
 id uuid primary key default gen_random_uuid(), tenant_code text not null, institution_id text not null, input_id uuid not null, allowed boolean not null, capabilities jsonb not null, obligations jsonb not null, warnings jsonb not null default '[]'::jsonb, checksum_sha256 text not null check(checksum_sha256 ~ '^[a-f0-9]{64}$'), evaluated_by_subject text not null, evaluated_at timestamptz not null default now(), unique(tenant_code,institution_id,id), foreign key(tenant_code,institution_id,input_id) references school_operation_policy_inputs(tenant_code,institution_id,id) on delete restrict, check(jsonb_typeof(capabilities)='array' and jsonb_typeof(obligations)='array' and jsonb_typeof(warnings)='array')
);
create or replace function public.school_stage1b_snapshot_immutable() returns trigger language plpgsql as $$ begin raise exception 'school regulatory snapshots are immutable'; end $$;
create trigger school_policy_inputs_immutable before update or delete on school_operation_policy_inputs for each row execute function public.school_stage1b_snapshot_immutable();
create trigger school_policy_evaluations_v2_immutable before update or delete on school_operation_policy_evaluations_v2 for each row execute function public.school_stage1b_snapshot_immutable();
