import { fireEvent, render, screen, waitFor } from "@testing-library/react";
import { PrimeReactProvider } from "@primereact/core/config";
import { describe, expect, it, vi } from "vitest";
import { PortfolioIntertenantTransfer, type IntertenantPortfolioTransferApi } from "./PortfolioIntertenantTransfer";

const transfer = { id: "transfer-1", transfer_code: "TRF-2026-0001", source_institution: "Școala Sursă", destination_institution: "Școala Destinație", status: "trimis" };
function api(): IntertenantPortfolioTransferApi { return { destinations: vi.fn().mockResolvedValue([{ code: "tenant-destination", label: "Școala Destinație" }]), outgoing: vi.fn().mockResolvedValue({ items: [{ ...transfer, status: "pregatit" }], total: 1, page: 1, pageSize: 20 }), create: vi.fn().mockResolvedValue(transfer), send: vi.fn().mockResolvedValue(transfer), inbox: vi.fn().mockResolvedValue({ items: [transfer], total: 1, page: 1, pageSize: 20 }), accept: vi.fn().mockResolvedValue({ ...transfer, status: "receptionat" }) }; }
function view(client: IntertenantPortfolioTransferApi, capabilities = { send: true, receive: true }) { return render(<PrimeReactProvider><PortfolioIntertenantTransfer portfolioID="portfolio-1" api={client} capabilities={capabilities} /></PrimeReactProvider>); }
describe("PortfolioIntertenantTransfer", () => {
  it("loads source and destination views through their distinct capability-bound APIs", async () => { const client = api(); view(client); await screen.findAllByText("TRF-2026-0001"); expect(client.outgoing).toHaveBeenCalledWith("portfolio-1", expect.objectContaining({ page: 1, pageSize: 20 })); expect(client.inbox).toHaveBeenCalledWith(expect.objectContaining({ page: 1, pageSize: 20 })); });
  it("loads only server-authorized destinations and requires one before creation", async () => { const client = api(); view(client); const start = await screen.findByRole("button", { name: "Inițiază transfer" }); await waitFor(() => expect(start).toBeEnabled()); expect(client.destinations).toHaveBeenCalledOnce(); fireEvent.click(start); expect(screen.getAllByRole("button", { name: "Inițiază transfer" })[1]).toBeDisabled(); });
  it("requires professional confirmation before accepting an inbox package", async () => { const client = api(); view(client); fireEvent.click(await screen.findByRole("button", { name: "Acceptă" })); expect(screen.getByRole("button", { name: "Acceptă profesional" })).toBeDisabled(); fireEvent.click(screen.getByLabelText("Confirm primirea pachetului probatoriu")); fireEvent.click(screen.getByRole("button", { name: "Acceptă profesional" })); await waitFor(() => expect(client.accept).toHaveBeenCalledWith("transfer-1")); });
  it("does not reveal commands or call protected collections without their capability", async () => { const client = api(); view(client, { send: false, receive: false }); expect(await screen.findByText("Nu aveți capabilitatea de expediere inter-tenant.")).toBeInTheDocument(); expect(screen.getByText("Nu aveți capabilitatea de recepție inter-tenant.")).toBeInTheDocument(); expect(client.destinations).not.toHaveBeenCalled(); expect(client.outgoing).not.toHaveBeenCalled(); expect(client.inbox).not.toHaveBeenCalled(); });
});
