import { useState } from "react";
import { Button } from "@primereact/ui/button";
import { Card } from "@primereact/ui/card";
import { Message } from "@primereact/ui/message";
import { ProgressSpinner } from "@primereact/ui/progressspinner";
import type { EducationApi, PortfolioEvidenceManifestResponse } from "./types";

function formatDate(value: string) { return new Intl.DateTimeFormat("ro-RO", { dateStyle: "medium", timeStyle: "short" }).format(new Date(value)); }
function downloadManifest(result: PortfolioEvidenceManifestResponse) { const payload = JSON.stringify(result.manifest, null, 2); const url = URL.createObjectURL(new Blob([payload], { type: "application/json" })); const anchor = document.createElement("a"); anchor.href = url; anchor.download = `${result.manifest.portfolio.portfolio_code}-manifest-probatoriu.json`; anchor.click(); URL.revokeObjectURL(url); }

/** A server-authoritative evidence export: this never accepts UI-selected rows, hashes, or object keys. */
export function PortfolioExportManifestPanel({ portfolioID, api, canExport }: { portfolioID: string; api: Pick<EducationApi, "createPortfolioExportManifest">; canExport: boolean }) {
  const [result, setResult] = useState<PortfolioEvidenceManifestResponse>(); const [loading, setLoading] = useState(false); const [error, setError] = useState<string>();
  const generate = async () => { setLoading(true); setError(undefined); try { setResult(await api.createPortfolioExportManifest(portfolioID)); } catch (cause) { const code = cause instanceof Error ? cause.message : ""; setError(code === "education_portfolio_export_provenance_incomplete" ? "Exportul nu poate fi generat: serverul a detectat dovezi fără proveniență arhivistică verificabilă sau portofoliul nu este într-o stare exportabilă." : "Manifestul probatoriu nu a putut fi generat. Încercați din nou."); } finally { setLoading(false); } };
  if (!canExport) return null;
  return <Card.Root><Card.Body><Card.Title>Export probatoriu</Card.Title><Card.Subtitle>Manifest imutabil, derivat exclusiv de server din portofoliu și versiunile eArhivă.</Card.Subtitle><Card.Content><div className="flex flex-col gap-3">{error && <Message.Root severity="error"><Message.Content><Message.Text>{error}</Message.Text></Message.Content></Message.Root>}{!result ? <div className="flex flex-wrap items-center gap-2"><Button disabled={loading} onClick={() => void generate()}><i className="pi pi-file-export" aria-hidden="true" />Generează manifest probatoriu</Button>{loading && <ProgressSpinner.Root aria-label="Se generează manifestul"><ProgressSpinner.Range><ProgressSpinner.Track /><ProgressSpinner.Value /></ProgressSpinner.Range></ProgressSpinner.Root>}</div> : <><Message.Root severity="success"><Message.Content><Message.Text>Manifestul a fost generat și înregistrat în audit. Descărcarea conține exact conținutul returnat de server.</Message.Text></Message.Content></Message.Root><div className="grid gap-2 sm:grid-cols-2"><span><strong>Portofoliu:</strong> {result.manifest.portfolio.portfolio_code}</span><span><strong>Generat:</strong> {formatDate(result.generated_at)}</span><span><strong>Algoritm:</strong> {result.manifest.hash_algorithm}</span><span><strong>Documente:</strong> {result.manifest.documents.length}</span><span className="sm:col-span-2 break-all"><strong>SHA-256:</strong> {result.manifest.manifest_sha256}</span></div><div className="flex flex-wrap gap-2"><Button size="small" onClick={() => downloadManifest(result)}><i className="pi pi-download" aria-hidden="true" />Descarcă manifest JSON</Button><Button size="small" variant="outlined" severity="secondary" disabled={loading} onClick={() => void generate()}><i className="pi pi-refresh" aria-hidden="true" />Regenerează</Button></div><section aria-label="Documente incluse în manifest" className="flex flex-col gap-2"><p className="m-0 text-sm text-muted-color">Colecție imutabilă inclusă în manifestul returnat de server; nu este un registru filtrabil sau paginabil.</p><ol className="m-0 flex list-none flex-col gap-2 p-0">{result.manifest.documents.map((document) => <li key={document.evidence_record_id}><Card.Root><Card.Body><Card.Title><span className="flex flex-wrap gap-2"><span>{document.chronological_no}.</span><span>{document.document_title}</span></span></Card.Title><Card.Content><dl className="grid gap-2 sm:grid-cols-3"><div><dt>Secțiune</dt><dd>{document.section_code}</dd></div><div><dt>Versiune</dt><dd>v{document.archive_version_no}</dd></div><div className="sm:col-span-3"><dt>Hash sursă</dt><dd className="break-all">{document.source_sha256}</dd></div></dl></Card.Content></Card.Body></Card.Root></li>)}</ol></section></>}</div></Card.Content></Card.Body></Card.Root>;
}
