import { fireEvent, render, screen, waitFor } from "@testing-library/react";
import { PrimeReactProvider } from "@primereact/core/config";
import { describe, expect, it, vi } from "vitest";
import type { ContractClient } from "../../api/client";
import { createPortfolioValorificationPackageApi, PortfolioValorificationPackageManager } from "./PortfolioValorificationPackageManager";

const packageRow = { id: "package-1", portfolio_id: "portfolio-1", institution_id: "institution-1", tenant_code: "tenant", scope: "evaluare_profesionala", purpose: "definitivat", status: "draft", created_at: "2026-09-10T10:00:00Z", created_by_subject: "user-1" };
const result = <T,>(data: T) => ({ data, response: new Response(JSON.stringify(data), { status: 200 }) });
function client() { const GET = vi.fn((path: string) => Promise.resolve(path.includes("eligible-sources") ? result([{ id: "evaluation-1", label: "Evaluare anuală", scope: "evaluare_profesionala" }]) : path.includes("eligible-archive-versions") ? result([{ archive_document_id: "archive-doc-1", archive_version_id: "archive-version-1", title: "Raport", version_no: 3 }]) : path.endsWith("/documents") ? result([]) : result({ items: [packageRow], total: 22, page: 1, pageSize: 20 }))); const POST = vi.fn((path: string) => Promise.resolve(path.endsWith("/valorification-packages") ? result(packageRow) : result(packageRow))); return { GET, POST } as unknown as ContractClient & { GET: ReturnType<typeof vi.fn>; POST: ReturnType<typeof vi.fn> }; }
function view(apiClient: ContractClient, capabilities = { read: true, manage: true }) { return render(<PrimeReactProvider><PortfolioValorificationPackageManager portfolioID="portfolio-1" client={apiClient} capabilities={capabilities} /></PrimeReactProvider>); }

describe("PortfolioValorificationPackageManager", () => {
  it("uses generated list parameters for server pagination and filters", async () => { const apiClient = client(); view(apiClient); await screen.findByText("Evaluare profesională"); expect(apiClient.GET).toHaveBeenCalledWith("/api/education/portfolios/records/{recordID}/valorification-packages", expect.objectContaining({ params: expect.objectContaining({ path: { recordID: "portfolio-1" }, query: expect.objectContaining({ page: 1, pageSize: 20 }) }) })); fireEvent.click(screen.getByRole("button", { name: "Următor" })); await waitFor(() => expect(apiClient.GET).toHaveBeenLastCalledWith("/api/education/portfolios/records/{recordID}/valorification-packages", expect.objectContaining({ params: expect.objectContaining({ query: expect.objectContaining({ page: 2 }) }) }))); });
  it("loads eligible sources only after opening the creation wizard", async () => { const apiClient = client(); view(apiClient); await screen.findByText("Evaluare profesională"); fireEvent.click(screen.getByRole("button", { name: "Adaugă pachet" })); await screen.findByText("Selectați scopul juridic și sursa eligibilă furnizată de server."); expect(apiClient.GET).toHaveBeenCalledWith("/api/education/portfolios/records/{recordID}/valorification-packages/eligible-sources", expect.objectContaining({ params: expect.objectContaining({ path: { recordID: "portfolio-1" }, query: { scope: "evaluare_profesionala" } }) })); });
  it("offers distinction or award for both evaluation and merit source scopes accepted by the backend", async () => { const apiClient = client(); view(apiClient); await screen.findByText("Evaluare profesională"); fireEvent.click(screen.getByRole("button", { name: "Adaugă pachet" })); await screen.findByText("Selectați scopul juridic și sursa eligibilă furnizată de server."); fireEvent.click(screen.getByLabelText("Scop juridic")); expect(await screen.findByRole("option", { name: "Distincție sau premiu" })).toBeInTheDocument(); });
  it("does not expose mutation actions without management capability", async () => { const apiClient = client(); view(apiClient, { read: true, manage: false }); await screen.findByText("Evaluare profesională"); expect(screen.queryByRole("button", { name: "Adaugă pachet" })).not.toBeInTheDocument(); expect(screen.queryByRole("button", { name: "submit evaluare_profesionala" })).not.toBeInTheDocument(); });
  it("does not issue a list request without read capability", async () => { const apiClient = client(); view(apiClient, { read: false, manage: false }); expect(await screen.findByText("Nu aveți capabilitatea de consultare a pachetelor de valorificare.")).toBeInTheDocument(); expect(apiClient.GET).not.toHaveBeenCalled(); });
  it("keeps create, attach, transition and evidence operations on their generated literal contracts", async () => {
    const apiClient = client();
    const api = createPortfolioValorificationPackageApi(apiClient);
    await api.create("portfolio-1", "evaluare_profesionala", "definitivat", "evaluation-1");
    expect(apiClient.POST).toHaveBeenCalledWith("/api/education/portfolios/records/{recordID}/valorification-packages", expect.objectContaining({ body: { scope: "evaluare_profesionala", purpose: "definitivat", source_evaluation_id: "evaluation-1" } }));
    await api.attach("portfolio-1", "package-1", { archive_document_id: "archive-doc-1", archive_version_id: "archive-version-1", title: "Raport", version_no: 3 });
    expect(apiClient.POST).toHaveBeenCalledWith("/api/education/portfolios/records/{recordID}/valorification-packages/{itemID}/documents", expect.objectContaining({ params: { path: { recordID: "portfolio-1", itemID: "package-1" } } }));
    await api.advance("portfolio-1", "package-1", "submit");
    expect(apiClient.POST).toHaveBeenCalledWith("/api/education/portfolios/records/{recordID}/valorification-packages/{itemID}/advance", expect.objectContaining({ body: { action: "submit" } }));
    await api.evidence("portfolio-1", "package-1");
    expect(apiClient.GET).toHaveBeenCalledWith("/api/education/portfolios/records/{recordID}/valorification-packages/{itemID}/documents", expect.objectContaining({ params: { path: { recordID: "portfolio-1", itemID: "package-1" } } }));
  });
});
