import { fireEvent, render, screen, waitFor } from "@testing-library/react";
import { PrimeReactProvider } from "@primereact/core/config";
import { describe, expect, it, vi } from "vitest";
import { PortfolioIntertenantTransfer, type IntertenantPortfolioTransferApi } from "./PortfolioIntertenantTransfer";

const transfer = { id: "transfer-1", transfer_code: "TRF-2026-0001", source_institution: "Școala Sursă", destination_institution: "Școala Destinație", status: "trimis", routing_version: 2 };
function api(): IntertenantPortfolioTransferApi { return { destinations: vi.fn().mockResolvedValue([{ code: "tenant-destination", label: "Școala Destinație" }]), outgoing: vi.fn().mockResolvedValue({ items: [{ ...transfer, status: "pregatit" }], total: 1, page: 1, pageSize: 20 }), create: vi.fn().mockResolvedValue(transfer), advance: vi.fn().mockResolvedValue(transfer), inbox: vi.fn().mockResolvedValue({ items: [transfer], total: 1, page: 1, pageSize: 20 }), accept: vi.fn().mockResolvedValue({ ...transfer, status: "receptionat" }) }; }
function view(client: IntertenantPortfolioTransferApi, capabilities = { send: true, receive: true }) { return render(<PrimeReactProvider><PortfolioIntertenantTransfer portfolioID="portfolio-1" api={client} capabilities={capabilities} /></PrimeReactProvider>); }
describe("PortfolioIntertenantTransfer", () => {
  it("loads source and destination views through their distinct capability-bound APIs", async () => { const client = api(); view(client); await screen.findAllByText("TRF-2026-0001"); expect(client.outgoing).toHaveBeenCalledWith("portfolio-1", expect.objectContaining({ page: 1, pageSize: 20 })); expect(client.inbox).toHaveBeenCalledWith(expect.objectContaining({ page: 1, pageSize: 20 })); });
  it("places creation in the outgoing action header and requires a server-authorized destination", async () => { const client = api(); view(client); const start = await screen.findByRole("button", { name: "Inițiază transfer" }); await waitFor(() => expect(start).toBeEnabled()); expect(start.closest("thead")).not.toBeNull(); expect(client.destinations).toHaveBeenCalledOnce(); fireEvent.click(start); expect(screen.getAllByRole("button", { name: "Inițiază transfer" })[1]).toBeDisabled(); });
  it("does not offer server-unsupported destination filtering in the transfer inbox", async () => { const client = api(); view(client); await screen.findAllByText("TRF-2026-0001"); expect(screen.queryByLabelText("Filtru inbox Instituție destinație")).not.toBeInTheDocument(); });
  it("requires professional confirmation before accepting an inbox package", async () => { const client = api(); view(client); fireEvent.click(await screen.findByRole("button", { name: "Acceptă" })); expect(screen.getByRole("button", { name: "Acceptă profesional" })).toBeDisabled(); fireEvent.click(screen.getByLabelText("Confirm primirea pachetului probatoriu")); fireEvent.click(screen.getByRole("button", { name: "Acceptă profesional" })); await waitFor(() => expect(client.accept).toHaveBeenCalledWith("transfer-1")); });
  it("sends the documented advance action for each eligible source-side lifecycle state", async () => { const client = api(); client.outgoing = vi.fn().mockResolvedValue({ items: [{ ...transfer, status: "pregatit", routing_version: 2 }, { ...transfer, id: "legacy", transfer_code: "TRF-legacy", status: "trimis", routing_version: 1 }, { ...transfer, id: "received", transfer_code: "TRF-received", status: "receptionat", routing_version: 2 }], total: 3, page: 1, pageSize: 20 }); view(client); fireEvent.click(await screen.findByRole("button", { name: "Marchează trimis TRF-2026-0001" })); await waitFor(() => expect(client.advance).toHaveBeenCalledWith("portfolio-1", "transfer-1", "mark_sent")); fireEvent.click(screen.getByRole("button", { name: "Confirmă recepția TRF-legacy" })); await waitFor(() => expect(client.advance).toHaveBeenCalledWith("portfolio-1", "legacy", "confirm_received")); fireEvent.click(screen.getByRole("button", { name: "Închide transferul TRF-received" })); await waitFor(() => expect(client.advance).toHaveBeenCalledWith("portfolio-1", "received", "close_transfer")); });
  it("does not expose a legacy advance command for a version-two sent package", async () => { const client = api(); client.outgoing = vi.fn().mockResolvedValue({ items: [transfer], total: 1, page: 1, pageSize: 20 }); view(client); await screen.findAllByText("TRF-2026-0001"); expect(screen.queryByRole("button", { name: /Confirmă recepția/ })).not.toBeInTheDocument(); });
  it("does not reveal commands or call protected collections without their capability", async () => { const client = api(); view(client, { send: false, receive: false }); expect(await screen.findByText("Nu aveți capabilitatea de expediere inter-tenant.")).toBeInTheDocument(); expect(screen.getByText("Nu aveți capabilitatea de recepție inter-tenant.")).toBeInTheDocument(); expect(client.destinations).not.toHaveBeenCalled(); expect(client.outgoing).not.toHaveBeenCalled(); expect(client.inbox).not.toHaveBeenCalled(); });
});
