package education

import (
	"crypto/sha256"
	"encoding/hex"
	"testing"
)

func TestPortfolioExportGeneratedFilesBindExactSerializedBytes(t *testing.T) {
	portfolio := PortfolioRecord{
		ID: "portfolio-1", PortfolioCode: "PORT-1", OwnerName: "Teacher", SchoolYear: "2026-2027", Status: "draft", InstitutionID: "inst-1",
	}
	opis := []PortfolioOpisEntry{{
		ID: "opis-1", PortfolioID: portfolio.ID, SectionCode: "identificare_profesionala", ComponentCode: "structura_cadru",
		EntryTitle: "Dovada", ChronologicalIndex: 1, CheckedOn: "2026-09-12", InstitutionID: portfolio.InstitutionID,
	}}
	manifest := PortfolioExportManifest{
		ManifestVersion: portfolioExportManifestVersion,
		HashAlgorithm:   "SHA-256",
		TenantCode:      "tenant-1",
		InstitutionID:   portfolio.InstitutionID,
		Portfolio:       PortfolioExportManifestPortfolio{ID: portfolio.ID, PortfolioCode: portfolio.PortfolioCode, SchoolYear: portfolio.SchoolYear, Status: portfolio.Status},
		Documents:       []PortfolioExportManifestDocument{},
	}

	bound, err := portfolioExportManifestWithGeneratedFiles(manifest, portfolio, opis)
	if err != nil {
		t.Fatalf("bind generated files: %v", err)
	}
	generated, err := portfolioExportGeneratedPayloads(portfolio, opis)
	if err != nil {
		t.Fatalf("serialize generated files: %v", err)
	}
	wantPaths := []string{"portfolio.json", "opis.json", "opis.txt"}
	if len(bound.GeneratedFiles) != len(wantPaths) || len(generated) != len(wantPaths) {
		t.Fatalf("generated file count: manifest=%d payloads=%d want=%d", len(bound.GeneratedFiles), len(generated), len(wantPaths))
	}
	for index, path := range wantPaths {
		digest := sha256.Sum256(generated[index].Payload)
		descriptor := bound.GeneratedFiles[index]
		if generated[index].ZIPPath != path || descriptor.ZIPPath != path || descriptor.SizeBytes != int64(len(generated[index].Payload)) || descriptor.SHA256 != hex.EncodeToString(digest[:]) {
			t.Fatalf("descriptor %d does not bind exact generated bytes: descriptor=%#v payload=%#v", index, descriptor, generated[index])
		}
	}
	if !portfolioExportGeneratedFilesMatch(bound.GeneratedFiles, generated) {
		t.Fatal("fresh generated bytes must match their manifest descriptors")
	}
	if bound.ManifestSHA256 != portfolioExportManifestSHA256(bound) {
		t.Fatal("bound manifest checksum is not its canonical checksum")
	}

	tampered := make([]portfolioExportGeneratedPayload, len(generated))
	copy(tampered, generated)
	tampered[2].Payload = append([]byte(nil), generated[2].Payload...)
	tampered[2].Payload[len(tampered[2].Payload)-1] ^= 1
	if portfolioExportGeneratedFilesMatch(bound.GeneratedFiles, tampered) {
		t.Fatal("generated file verification accepted tampered OPIS text bytes")
	}
}
