import type { Fetcher, Page } from '../workflow/api';

export interface ArchiveDocument { id: string; title: string; original_file_name: string; mime_type: string; source_kind: string; source_system: string; external_reference: string; taxonomy_code?: string | null; taxonomy_label?: string | null; status: string; document_date?: string | null; metadata?: Record<string, unknown>; current_version_no: number; received_at: string; created_at: string; updated_at: string; score?: number; snippet?: string }
export interface ArchiveDocumentDetail extends ArchiveDocument { latest_version?: ArchiveDocumentVersion }
export interface ArchiveDocumentVersion { id: string; document_id: string; version_no: number; source_sha256: string; source_size_bytes: number; page_count: number; text_status: string; created_at: string; chunk_count?: number }
export interface ArchiveTaxonomy { id: string; parent_id?: string | null; code: string; label: string; description: string; path: string; active: boolean; sort_order: number }
export type SearchMode = 'fts' | 'vector' | 'hybrid';
export interface ArchiveSearch { q?: string; mode?: SearchMode; status?: string; source_kind?: string; taxonomy_code?: string; document_date_from?: string; document_date_to?: string; received_at_from?: string; received_at_to?: string; page?: string; pageSize?: string; sort?: string; direction?: string }
export interface UploadArchiveDocumentInput { file: File; title: string; source_kind: string; source_system?: string; external_reference?: string; taxonomy_code?: string; taxonomy_label?: string; taxonomy_parent?: string; document_date?: string; metadata?: Record<string, unknown> }
export interface ArchiveJob { id: string; document_id?: string; version_id?: string; job_type?: string; stage?: string; status: string; attempts: number; has_error?: boolean; error_summary?: string; created_at?: string; available_at?: string; updated_at?: string; started_at?: string; finished_at?: string }
export interface ArchiveAdminHealth { storage_enabled: boolean; storage: { status: string; message?: string }; ocr: { configured: boolean; provider: string; status: string; message?: string }; queue: { pending: number; running: number; succeeded: number; failed: number } }
export interface ArchiveAdminStats { documents_by_status: Record<string, number>; jobs_by_status: Record<string, number>; total_documents: number; total_bytes: number; total_pages: number; total_jobs: number; queued: number; processing: number; completed: number; failed: number }
export type ArchiveClassificationReviewFilterState = 'pending_review' | 'needs_review';
export type ArchiveClassificationReviewState = ArchiveClassificationReviewFilterState | 'approved' | 'corrected';
export interface ArchiveClassificationField { value?: string; source: string; confidence: number; evidence?: string }
export interface ArchiveClassificationSuggestion { category: ArchiveClassificationField; fond: ArchiveClassificationField; series: ArchiveClassificationField; document_type: ArchiveClassificationField; document_date: ArchiveClassificationField; document_number: ArchiveClassificationField }
export interface ArchiveFinalClassification { category: string; fond: string; series: string; document_type: string; document_date?: string; document_number?: string }
export interface ArchiveClassificationReview { id: string; document_id: string; version_id: string; state: ArchiveClassificationReviewState; revision: number; suggestion: ArchiveClassificationSuggestion; suggestion_confidence: number; suggestion_source: string; requires_human_review: boolean; generated_at: string; reviewed_at?: string; reviewed_by?: string; final_classification?: ArchiveFinalClassification; review_note?: string }
export interface ArchiveClassificationReviewDecision { revision: number; note: string; classification?: ArchiveFinalClassification }
export interface ArchiveApi { documents(query?: ArchiveSearch): Promise<Page<ArchiveDocument>>; document(id: string): Promise<ArchiveDocumentDetail>; versions(id: string): Promise<ArchiveDocumentVersion[]>; download(id: string): Promise<Blob>; taxonomy(query?: Record<string, string>): Promise<ArchiveTaxonomy[]>; upload(input: UploadArchiveDocumentInput): Promise<ArchiveDocumentDetail>; adminHealth(): Promise<ArchiveAdminHealth>; adminStats(): Promise<ArchiveAdminStats>; adminJobs(query?: Record<string, string>): Promise<Page<ArchiveJob>>; retryJob(jobId: string): Promise<ArchiveJob>; classificationReviews(query?: { state: ArchiveClassificationReviewFilterState; page?: string; pageSize?: string }): Promise<Page<ArchiveClassificationReview>>; approveClassificationReview(reviewId: string, input: Pick<ArchiveClassificationReviewDecision, 'revision' | 'note'>): Promise<ArchiveClassificationReview>; correctClassificationReview(reviewId: string, input: Required<ArchiveClassificationReviewDecision>): Promise<ArchiveClassificationReview> }

const page = <T,>(value: T[] | (Partial<Page<T>> & { page_size?: number })): Page<T> => Array.isArray(value) ? { items: value, total: value.length, page: 1, pageSize: value.length } : { items: value.items ?? [], total: Number(value.total ?? 0), page: Number(value.page ?? 1), pageSize: Number(value.pageSize ?? value.page_size ?? 25) };

export function createArchiveApi(fetcher: Fetcher = fetch, apiBase = '/api'): ArchiveApi {
  const request = async <T,>(path: string, init?: RequestInit) => { const response = await fetcher(`${apiBase}${path}`, { credentials: 'include', ...init, headers: { Accept: 'application/json', ...(init?.headers ?? {}) } }); if (!response.ok) throw new Error(`earchiva_request_${response.status}`); return response.json() as Promise<T>; };
  const query = (path: string, input: Record<string, string | undefined>) => { const params = new URLSearchParams(); Object.entries(input).forEach(([key, value]) => { if (value?.trim()) params.set(key, value); }); const encoded = params.toString(); return encoded ? `${path}?${encoded}` : path; };
  return {
    documents: async (input = {}) => page(await request<ArchiveDocument[] | Partial<Page<ArchiveDocument>>>(query('/earchiva/documents', { page: '1', pageSize: '25', ...input }))),
    document: (id) => request(`/earchiva/documents/${encodeURIComponent(id)}`), versions: (id) => request(`/earchiva/documents/${encodeURIComponent(id)}/versions`),
    async download(id) { const response = await fetcher(`${apiBase}/earchiva/documents/${encodeURIComponent(id)}/content`, { credentials: 'include', headers: { Accept: 'application/pdf' } }); if (!response.ok) throw new Error(`earchiva_request_${response.status}`); return response.blob(); },
    taxonomy: (input = {}) => request(query('/earchiva/taxonomy', input)),
    async upload(input) { const data = new FormData(); data.set('file', input.file); data.set('title', input.title); data.set('source_kind', input.source_kind); if (input.source_system) data.set('source_system', input.source_system); if (input.external_reference) data.set('external_reference', input.external_reference); if (input.taxonomy_code) data.set('taxonomy_code', input.taxonomy_code); if (input.taxonomy_label) data.set('taxonomy_label', input.taxonomy_label); if (input.taxonomy_parent) data.set('taxonomy_parent_code', input.taxonomy_parent); if (input.document_date) data.set('document_date', input.document_date); if (input.metadata) data.set('metadata', JSON.stringify(input.metadata)); return request('/earchiva/documents', { method: 'POST', body: data }); },
    adminHealth: () => request('/earchiva/admin/health'), adminStats: () => request('/earchiva/admin/stats'), adminJobs: async (input = {}) => page(await request<ArchiveJob[] | Partial<Page<ArchiveJob>>>(query('/earchiva/admin/jobs', input))), retryJob: (jobId) => request(`/earchiva/admin/jobs/${encodeURIComponent(jobId)}/retry`, { method: 'POST' }),
    classificationReviews: async (input) => page(await request<ArchiveClassificationReview[] | Partial<Page<ArchiveClassificationReview>>>(query('/earchiva/classification-reviews', { page: '1', pageSize: '25', ...input }))),
    approveClassificationReview: (reviewId, input) => request(`/earchiva/classification-reviews/${encodeURIComponent(reviewId)}/approve`, { method: 'POST', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify(input) }),
    correctClassificationReview: (reviewId, input) => request(`/earchiva/classification-reviews/${encodeURIComponent(reviewId)}/correct`, { method: 'POST', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify(input) }),
  };
}
