import { useCallback, useEffect, useRef, useState, type ChangeEvent } from 'react';
import { Button } from '@primereact/ui/button';
import { Card } from '@primereact/ui/card';
import { DataTable } from '@primereact/ui/datatable';
import { Dialog } from '@primereact/ui/dialog';
import { FileUpload } from '@primereact/ui/fileupload';
import { InputText } from '@primereact/ui/inputtext';
import { Message } from '@primereact/ui/message';
import { ProgressSpinner } from '@primereact/ui/progressspinner';
import { Select } from '@primereact/ui/select';
import { Tag } from '@primereact/ui/tag';
import type { FileUploadSelectEvent } from 'primereact/fileupload';
import type { SelectValueChangeEvent } from 'primereact/select';
import { createArchiveApi, type ArchiveApi, type ArchiveAdminHealth, type ArchiveAdminStats, type ArchiveDocument, type ArchiveDocumentDetail, type ArchiveDocumentVersion, type ArchiveJob, type ArchiveTaxonomy, type SearchMode, type UploadArchiveDocumentInput } from './api';
import { ClassificationReviewPanel } from './ClassificationReviewPanel';

const PAGE_SIZE = 25;
const MAX_PDF_BYTES = 100 * 1024 * 1024;
const Spinner = () => <ProgressSpinner.Root><ProgressSpinner.Range><ProgressSpinner.Track /><ProgressSpinner.Value /></ProgressSpinner.Range></ProgressSpinner.Root>;
const options = (items: string[]) => items.map((value) => ({ label: value, value }));
const cleanTitle = (name: string) => name.replace(/\.pdf$/i, '').replace(/[_.-]+/g, ' ').replace(/\s+/g, ' ').trim();

type UploadItem = { key: string; file: File; title: string; state: 'pending' | 'uploading' | 'queued' | 'processed' | 'failed'; error?: string; documentId?: string };
export const archiveUploadOutcome = (status: string): 'processed' | 'failed' | undefined => status === 'ready' || status === 'archived' ? 'processed' : status === 'failed' ? 'failed' : undefined;

export function ArchiveWorkspace({ api = createArchiveApi(), canManage = false, canReadContent = false, canReview = false }: { api?: ArchiveApi; canManage?: boolean; canReadContent?: boolean; canReview?: boolean }) {
  const [documents, setDocuments] = useState<ArchiveDocument[]>([]); const [taxonomy, setTaxonomy] = useState<ArchiveTaxonomy[]>([]);
  const [total, setTotal] = useState(0); const [page, setPage] = useState(1); const [query, setQuery] = useState(''); const [mode, setMode] = useState<SearchMode>('hybrid');
  const [status, setStatus] = useState(''); const [sourceKind, setSourceKind] = useState(''); const [taxonomyCode, setTaxonomyCode] = useState(''); const [loading, setLoading] = useState(true);
  const [error, setError] = useState<string>(); const [notice, setNotice] = useState<string>(); const [detail, setDetail] = useState<ArchiveDocumentDetail>(); const [versions, setVersions] = useState<ArchiveDocumentVersion[]>([]);
  const requestId = useRef(0);
  const load = useCallback(async () => { const id = ++requestId.current; setLoading(true); setError(undefined); try {
    const [nextDocuments, nextTaxonomy] = await Promise.all([api.documents({ q: query, mode, status, source_kind: sourceKind, taxonomy_code: taxonomyCode, page: String(page), pageSize: String(PAGE_SIZE), sort: 'updated_at', direction: 'desc' }), api.taxonomy({ active: 'true' })]);
    if (id !== requestId.current) return; setDocuments(nextDocuments.items); setTotal(nextDocuments.total); setTaxonomy(nextTaxonomy);
  } catch { if (id === requestId.current) setError('Documentele nu au putut fi încărcate. Reîncercați.'); } finally { if (id === requestId.current) setLoading(false); } }, [api, mode, page, query, sourceKind, status, taxonomyCode]);
  useEffect(() => { void load(); }, [load]);
  const showDetail = async (documentId: string) => { const id = ++requestId.current; setError(undefined); try { const [next, nextVersions] = await Promise.all([api.document(documentId), api.versions(documentId)]); if (id !== requestId.current) return; setDetail(next); setVersions(nextVersions); } catch { if (id === requestId.current) setError('Detaliile documentului nu au putut fi încărcate.'); } };
  const download = async (document: ArchiveDocumentDetail) => { setError(undefined); try { const blob = await api.download(document.id); const href = URL.createObjectURL(blob); const anchor = window.document.createElement('a'); anchor.href = href; anchor.download = `archive-${document.id}.pdf`; anchor.click(); URL.revokeObjectURL(href); } catch { setError('Originalul PDF nu a putut fi descărcat.'); } };
  const updateFilter = (set: (value: string) => void, value: string) => { set(value); setPage(1); };
  const knownStatuses = [...new Set(documents.map((item) => item.status).filter(Boolean))];
  const knownSources = [...new Set(documents.map((item) => item.source_kind).filter(Boolean))];
  return <section aria-label="eArhivă" className="flex flex-col gap-4">
    <Card.Root><Card.Body><Card.Title>eArhivă</Card.Title><Card.Content><div className="flex flex-col gap-3 lg:flex-row lg:flex-wrap">
      <InputText aria-label="Caută în arhivă" value={query} onChange={(event: ChangeEvent<HTMLInputElement>) => updateFilter(setQuery, event.target.value)} placeholder="Caută în titlu și text OCR" />
      <Select.Root value={mode} options={options(['hybrid', 'fts', 'vector'])} optionLabel="label" optionValue="value" onValueChange={(event: SelectValueChangeEvent) => { setMode(event.value as SearchMode); setPage(1); }}><Select.Trigger aria-label="Mod căutare"><Select.Value /><Select.Indicator /></Select.Trigger><Select.Portal><Select.Positioner><Select.Popup><Select.List /></Select.Popup></Select.Positioner></Select.Portal></Select.Root>
      <Select.Root value={status || null} options={options(knownStatuses)} optionLabel="label" optionValue="value" onValueChange={(event: SelectValueChangeEvent) => updateFilter(setStatus, String(event.value ?? ''))}><Select.Trigger aria-label="Stare"><Select.Value placeholder="Toate stările" /><Select.Indicator /></Select.Trigger><Select.Portal><Select.Positioner><Select.Popup><Select.List /></Select.Popup></Select.Positioner></Select.Portal></Select.Root>
      <Select.Root value={sourceKind || null} options={options(knownSources)} optionLabel="label" optionValue="value" onValueChange={(event: SelectValueChangeEvent) => updateFilter(setSourceKind, String(event.value ?? ''))}><Select.Trigger aria-label="Tip sursă"><Select.Value placeholder="Toate sursele" /><Select.Indicator /></Select.Trigger><Select.Portal><Select.Positioner><Select.Popup><Select.List /></Select.Popup></Select.Positioner></Select.Portal></Select.Root>
      <Select.Root value={taxonomyCode || null} options={taxonomy.map((node) => ({ label: node.path || node.label, value: node.code }))} optionLabel="label" optionValue="value" onValueChange={(event: SelectValueChangeEvent) => updateFilter(setTaxonomyCode, String(event.value ?? ''))}><Select.Trigger aria-label="Taxonomie"><Select.Value placeholder="Toată taxonomia" /><Select.Indicator /></Select.Trigger><Select.Portal><Select.Positioner><Select.Popup><Select.List /></Select.Popup></Select.Positioner></Select.Portal></Select.Root>
      <Button variant="outlined" onClick={() => void load()}>Reîncarcă</Button>{canManage && <UploadDialog api={api} taxonomy={taxonomy} onComplete={() => { setNotice('Lotul a fost transmis pentru procesare.'); setPage(1); void load(); }} />}
    </div></Card.Content></Card.Body></Card.Root>
    {error && <Message.Root severity="error"><Message.Content><Message.Text>{error}</Message.Text></Message.Content></Message.Root>}
    {notice && <Message.Root severity="success"><Message.Content><Message.Text>{notice}</Message.Text></Message.Content></Message.Root>}
    <Card.Root><Card.Body><Card.Content>{loading ? <div className="flex justify-center p-8"><Spinner /></div> : <><DocumentTable documents={documents} onDetail={showDetail} /><Pager page={page} total={total} hasNext={documents.length === PAGE_SIZE} onPrevious={() => setPage((value) => Math.max(1, value - 1))} onNext={() => setPage((value) => value + 1)} /></>}</Card.Content></Card.Body></Card.Root>
    {canManage && <ArchiveAdministration api={api} />}
    {canReview && <ClassificationReviewPanel api={api} canReview={canReview} />}
    <DocumentDialog document={detail} versions={versions} canReadContent={canReadContent} onDownload={download} onClose={() => setDetail(undefined)} />
  </section>;
}

function Pager({ page, total, hasNext, onPrevious, onNext }: { page: number; total: number; hasNext: boolean; onPrevious: () => void; onNext: () => void }) { return <div className="mt-3 flex items-center justify-between gap-2"><span>{total} rezultate · pagina {page}</span><div className="flex gap-2"><Button size="small" variant="outlined" disabled={page <= 1} onClick={onPrevious}>Anterior</Button><Button size="small" variant="outlined" disabled={!hasNext} onClick={onNext}>Următor</Button></div></div>; }
function DocumentTable({ documents, onDetail }: { documents: ArchiveDocument[]; onDetail: (id: string) => void }) { return documents.length === 0 ? <Message.Root severity="info"><Message.Content><Message.Text>Nu există documente pentru criteriile alese.</Message.Text></Message.Content></Message.Root> : <DataTable.Root data={documents as unknown as Record<string, unknown>[]} dataKey="id" scrollable><DataTable.Table><DataTable.THead><DataTable.THeadRow><DataTable.THeadCell>Titlu</DataTable.THeadCell><DataTable.THeadCell>Fișier original</DataTable.THeadCell><DataTable.THeadCell>Taxonomie</DataTable.THeadCell><DataTable.THeadCell>Stare</DataTable.THeadCell><DataTable.THeadCell>Relevanță</DataTable.THeadCell><DataTable.THeadCell>Acțiuni</DataTable.THeadCell></DataTable.THeadRow></DataTable.THead><DataTable.TBody>{({ item, index }) => { const document = item as unknown as ArchiveDocument; return <DataTable.Row key={document.id} index={index}><DataTable.Cell><div>{document.title}</div>{document.snippet && <small>{document.snippet}</small>}</DataTable.Cell><DataTable.Cell>{document.original_file_name}</DataTable.Cell><DataTable.Cell>{document.taxonomy_label ?? document.taxonomy_code ?? '—'}</DataTable.Cell><DataTable.Cell><Tag value={document.status} /></DataTable.Cell><DataTable.Cell>{document.score?.toFixed(2) ?? '—'}</DataTable.Cell><DataTable.Cell><Button size="small" variant="text" onClick={() => onDetail(document.id)}>Detalii</Button></DataTable.Cell></DataTable.Row>; }}</DataTable.TBody></DataTable.Table></DataTable.Root>; }

function UploadDialog({ api, taxonomy, onComplete }: { api: ArchiveApi; taxonomy: ArchiveTaxonomy[]; onComplete: () => void }) {
  const [open, setOpen] = useState(false); const [queue, setQueue] = useState<UploadItem[]>([]); const [sourceKind, setSourceKind] = useState('scan'); const [taxonomyCode, setTaxonomyCode] = useState(''); const [uploading, setUploading] = useState(false);
  const enqueue = (event: FileUploadSelectEvent) => { const pdfs = event.files.filter((file) => file.type === 'application/pdf' || /\.pdf$/i.test(file.name)); setQueue((current) => [...current, ...pdfs.map((file, index): UploadItem => ({ key: `${file.name}-${file.size}-${Date.now()}-${index}`, file, title: cleanTitle(file.name), state: file.size <= MAX_PDF_BYTES ? 'pending' : 'failed', error: file.size <= MAX_PDF_BYTES ? undefined : 'Depășește limita de 100 MiB.' }))]); };
  useEffect(() => { const ids = queue.filter((item) => item.state === 'queued' && item.documentId).map((item) => item.documentId!); if (ids.length === 0) return; const check = async () => { const statuses = await Promise.all(ids.map(async (id) => [id, (await api.document(id)).status] as const)); setQueue((current) => current.map((item) => { const status = item.documentId ? statuses.find(([id]) => id === item.documentId)?.[1] : undefined; const outcome = status ? archiveUploadOutcome(status) : undefined; if (outcome === 'failed') return { ...item, state: 'failed', error: 'Procesarea OCR a eșuat; verificați coada de administrare.' }; if (outcome === 'processed') return { ...item, state: 'processed', error: undefined }; return item; })); }; void check().catch(() => undefined); const timer = window.setInterval(() => void check().catch(() => undefined), 5000); return () => window.clearInterval(timer); }, [api, queue]);
  const run = async (retry?: UploadItem) => { const targets = retry ? [retry] : queue.filter((item) => item.state === 'pending' || item.state === 'failed'); if (!sourceKind.trim() || targets.length === 0) return; setUploading(true); for (const target of targets) { setQueue((current) => current.map((item) => item.key === target.key ? { ...item, state: 'uploading', error: undefined } : item)); try { const node = taxonomy.find((entry) => entry.code === taxonomyCode); const result = await api.upload({ file: target.file, title: target.title.trim() || cleanTitle(target.file.name), source_kind: sourceKind.trim(), taxonomy_code: node?.code, taxonomy_label: node?.label, metadata: { original_file_name: target.file.name, import_mode: 'sequential_batch' } satisfies Record<string, unknown> }); setQueue((current) => current.map((item) => item.key === target.key ? { ...item, state: 'queued', documentId: result.id } : item)); } catch { setQueue((current) => current.map((item) => item.key === target.key ? { ...item, state: 'failed', error: 'Transmiterea a eșuat; reîncercați.' } : item)); } } setUploading(false); onComplete(); };
  return <><Button onClick={() => setOpen(true)}>Încarcă PDF-uri</Button><Dialog.Root open={open} onOpenChange={(event: { value?: boolean }) => !event.value && setOpen(false)}><Dialog.Portal><Dialog.Backdrop /><Dialog.Positioner><Dialog.Popup><Dialog.Header><Dialog.Title>Import PDF în eArhivă</Dialog.Title><Dialog.Close aria-label="Închide" /></Dialog.Header><Dialog.Content><div className="flex flex-col gap-3"><Message.Root severity="info"><Message.Content><Message.Text>Fișierele sunt trimise pe rând, fără identificator de tenant sau cheie de stocare în browser. Numele original rămâne în proveniență; titlul propus este normalizat și poate fi ajustat. Starea de procesare este actualizată automat.</Message.Text></Message.Content></Message.Root><InputText aria-label="Tip sursă" value={sourceKind} onChange={(event: ChangeEvent<HTMLInputElement>) => setSourceKind(event.target.value)} placeholder="scan" /><Select.Root value={taxonomyCode || null} options={taxonomy.map((node) => ({ label: node.path || node.label, value: node.code }))} optionLabel="label" optionValue="value" onValueChange={(event: SelectValueChangeEvent) => setTaxonomyCode(String(event.value ?? ''))}><Select.Trigger aria-label="Taxonomie"><Select.Value placeholder="Fără taxonomie" /><Select.Indicator /></Select.Trigger><Select.Portal><Select.Positioner><Select.Popup><Select.List /></Select.Popup></Select.Positioner></Select.Portal></Select.Root><FileUpload.Root name="files" customUpload multiple accept="application/pdf,.pdf" maxFileSize={MAX_PDF_BYTES} disabled={uploading} onSelect={enqueue}><FileUpload.Trigger>Alege PDF-uri</FileUpload.Trigger><FileUpload.Content /></FileUpload.Root>{queue.length > 0 && <div className="flex flex-col gap-2">{queue.map((item) => <div key={item.key} className="flex flex-wrap items-center gap-2"><InputText aria-label={`Titlu pentru ${item.file.name}`} value={item.title} disabled={uploading} onChange={(event: ChangeEvent<HTMLInputElement>) => setQueue((current) => current.map((entry) => entry.key === item.key ? { ...entry, title: event.target.value } : entry))} /><span>{item.file.name}</span><Tag value={item.state} severity={item.state === 'failed' ? 'danger' : item.state === 'processed' ? 'success' : undefined} />{item.error && <span role="alert">{item.error}</span>}{item.state === 'failed' && <Button size="small" variant="text" disabled={uploading} onClick={() => void run(item)}>Reîncearcă</Button>}</div>)}</div>}</div></Dialog.Content><Dialog.Footer><div className="flex justify-end gap-2"><Button variant="outlined" onClick={() => setOpen(false)}>Închide</Button><Button disabled={uploading || !queue.some((item) => item.state === 'pending' || item.state === 'failed') || !sourceKind.trim()} onClick={() => void run()}>{uploading ? 'Se transmite…' : 'Transmite lotul'}</Button></div></Dialog.Footer></Dialog.Popup></Dialog.Positioner></Dialog.Portal></Dialog.Root></>;
}

function DocumentDialog({ document, versions, canReadContent, onDownload, onClose }: { document?: ArchiveDocumentDetail; versions: ArchiveDocumentVersion[]; canReadContent: boolean; onDownload: (document: ArchiveDocumentDetail) => Promise<void>; onClose: () => void }) { return <Dialog.Root open={Boolean(document)} onOpenChange={(event: { value?: boolean }) => !event.value && onClose()}><Dialog.Portal><Dialog.Backdrop /><Dialog.Positioner><Dialog.Popup><Dialog.Header><Dialog.Title>Document arhivistic</Dialog.Title><Dialog.Close aria-label="Închide" /></Dialog.Header><Dialog.Content>{document && <div className="flex flex-col gap-3"><dl><dt>Fișier original</dt><dd>{document.original_file_name}</dd><dt>Taxonomie</dt><dd>{document.taxonomy_label ?? document.taxonomy_code ?? '—'}</dd><dt>Stare</dt><dd>{document.status}</dd><dt>Primit</dt><dd>{document.received_at}</dd></dl><h3>Versiuni și procesare</h3>{versions.length ? <ul>{versions.map((version) => <li key={version.id}>v{version.version_no} · {version.text_status} · {version.page_count} pagini · {version.chunk_count ?? 0} fragmente</li>)}</ul> : <p>Nu există versiuni.</p>}</div>}</Dialog.Content><Dialog.Footer>{document && canReadContent && <Button onClick={() => void onDownload(document)}>Descarcă originalul PDF</Button>}<Button variant="outlined" onClick={onClose}>Închide</Button></Dialog.Footer></Dialog.Popup></Dialog.Positioner></Dialog.Portal></Dialog.Root>; }

function ArchiveAdministration({ api }: { api: ArchiveApi }) {
  const [health, setHealth] = useState<ArchiveAdminHealth>();
  const [stats, setStats] = useState<ArchiveAdminStats>();
  const [jobs, setJobs] = useState<ArchiveJob[]>([]);
  const [statusFilter, setStatusFilter] = useState('');
  const [retryCandidate, setRetryCandidate] = useState<ArchiveJob>();
  const [error, setError] = useState<string>();
  const [loading, setLoading] = useState(false);
  const load = useCallback(async () => {
    setLoading(true); setError(undefined);
    try {
      const [nextHealth, nextStats, nextJobs] = await Promise.all([
        api.adminHealth(), api.adminStats(), api.adminJobs({ page: '1', pageSize: '25', status: statusFilter }),
      ]);
      setHealth(nextHealth); setStats(nextStats); setJobs(nextJobs.items);
    } catch { setError('Administrarea eArhivă nu este disponibilă.'); }
    finally { setLoading(false); }
  }, [api, statusFilter]);
  useEffect(() => { void load(); }, [load]);
  const retry = async () => {
    if (!retryCandidate) return;
    try { await api.retryJob(retryCandidate.id); setRetryCandidate(undefined); await load(); }
    catch { setError('Reîncercarea jobului a eșuat.'); }
  };
  return <Card.Root><Card.Body><Card.Title>Administrare eArhivă</Card.Title><Card.Content><div className="flex flex-col gap-4">
    <div className="flex flex-wrap items-center gap-2"><Select.Root value={statusFilter || null} options={options(['pending', 'running', 'succeeded', 'failed'])} optionLabel="label" optionValue="value" onValueChange={(event: SelectValueChangeEvent) => setStatusFilter(String(event.value ?? ''))}><Select.Trigger aria-label="Filtrează joburile după stare"><Select.Value placeholder="Toate joburile" /><Select.Indicator /></Select.Trigger><Select.Portal><Select.Positioner><Select.Popup><Select.List /></Select.Popup></Select.Positioner></Select.Portal></Select.Root><Button variant="outlined" disabled={loading} onClick={() => void load()}>Actualizează</Button></div>
    {error && <Message.Root severity="error"><Message.Content><Message.Text>{error}</Message.Text></Message.Content></Message.Root>}
    {health && <div aria-label="Stare servicii" className="grid gap-3 md:grid-cols-2"><Card.Root><Card.Body><Card.Title>Storage</Card.Title><Card.Content><Tag value={health.storage?.status ?? 'necunoscut'} severity={health.storage_enabled ? 'info' : 'danger'} /><p>{health.storage?.message ?? 'Configurație disponibilă.'}</p></Card.Content></Card.Body></Card.Root><Card.Root><Card.Body><Card.Title>OCR</Card.Title><Card.Content><Tag value={`${health.ocr?.provider ?? 'OCR'}: ${health.ocr?.status ?? 'necunoscut'}`} severity={health.ocr?.configured ? 'info' : 'danger'} /><p>{health.ocr?.message ?? 'Configurație disponibilă.'}</p></Card.Content></Card.Body></Card.Root></div>}
    {stats && <div aria-label="Statistici eArhivă" className="flex flex-wrap gap-2"><Tag value={`Documente: ${stats.total_documents}`} /><Tag value={`Pagini: ${stats.total_pages}`} /><Tag value={`În așteptare: ${stats.queued}`} /><Tag value={`În procesare: ${stats.processing}`} /><Tag value={`Finalizate: ${stats.completed}`} /><Tag value={`Eșuate: ${stats.failed}`} severity={stats.failed ? 'danger' : undefined} /></div>}
    {jobs.length === 0 ? <Message.Root severity="info"><Message.Content><Message.Text>Nu există joburi pentru filtrul ales.</Message.Text></Message.Content></Message.Root> : <DataTable.Root data={jobs as unknown as Record<string, unknown>[]} dataKey="id"><DataTable.Table><DataTable.THead><DataTable.THeadRow><DataTable.THeadCell>Job</DataTable.THeadCell><DataTable.THeadCell>Etapă</DataTable.THeadCell><DataTable.THeadCell>Stare</DataTable.THeadCell><DataTable.THeadCell>Încercări</DataTable.THeadCell><DataTable.THeadCell>Acțiune</DataTable.THeadCell></DataTable.THeadRow></DataTable.THead><DataTable.TBody>{({ item, index }) => { const job = item as unknown as ArchiveJob; return <DataTable.Row key={job.id} index={index}><DataTable.Cell>{job.id}</DataTable.Cell><DataTable.Cell>{job.stage ?? job.job_type ?? '—'}</DataTable.Cell><DataTable.Cell><Tag value={job.status} /></DataTable.Cell><DataTable.Cell>{job.attempts}</DataTable.Cell><DataTable.Cell><Button size="small" variant="text" disabled={loading || job.status !== 'failed'} onClick={() => setRetryCandidate(job)}>Reîncearcă</Button></DataTable.Cell></DataTable.Row>; }}</DataTable.TBody></DataTable.Table></DataTable.Root>}
    <Dialog.Root open={Boolean(retryCandidate)} onOpenChange={(event: { value?: boolean }) => !event.value && setRetryCandidate(undefined)}><Dialog.Portal><Dialog.Backdrop /><Dialog.Positioner><Dialog.Popup><Dialog.Header><Dialog.Title>Confirmă reîncercarea</Dialog.Title><Dialog.Close aria-label="Închide" /></Dialog.Header><Dialog.Content>Jobul va fi repus în coada OCR de la prima încercare.</Dialog.Content><Dialog.Footer><Button variant="outlined" onClick={() => setRetryCandidate(undefined)}>Renunță</Button><Button onClick={() => void retry()}>Reîncearcă jobul</Button></Dialog.Footer></Dialog.Popup></Dialog.Positioner></Dialog.Portal></Dialog.Root>
  </div></Card.Content></Card.Body></Card.Root>;
}
