export type EducationStatusSeverity = 'success' | 'info' | 'warn' | 'danger' | 'secondary';

const SUCCESS_STATUSES = new Set([
  'approved',
  'published',
  'validated',
  'active',
  'finalized',
  'funded',
  'completed',
  'held',
  'reviewed',
  'true',
  'implemented',
  'received',
  'prezent',
  'verificat',
  'publicat',
  'adoptat',
  'complet',
  'activ',
  'finalizata',
  'nu_este_necesara',
  'receptionat',
  'inchis',
  'acceptat',
  'realizat',
  'accepted',
  'resolved',
  'semnat',
  'transmis',
  'confirmat',
  'admis',
  'finantat',
  'solutionat',
  'foarte_bine',
  'bine',
]);

const WARN_STATUSES = new Set([
  'draft',
  'scheduled',
  'submitted',
  'in_review',
  'review',
  'in_progress',
  'partial',
  'consultation',
  'consultare',
  'pending',
  'pending_anonymization',
  'internal',
  'prepared',
  'sent',
  'endorsed',
  'working_group',
  'cp_endorsed',
  'ca_approved',
  'registered',
  'none',
  'invitat',
  'declarat',
  'intern',
  'anonimizare_necesara',
  'portofoliu',
  'dosar_personal',
  'dosar_director',
  'dosar_director_adjunct',
  'amanat',
  'in_verificare',
  'pregatit_publicare',
  'necesara',
  'pregatit',
  'trimis',
  'depunere',
  'verificare_secretariat',
  'validare_manageriala',
  'reverificare',
  'completari',
  'de_stabilit',
  'in_urmarire',
  'preluare',
  'transfer',
  'arhivare',
  'restituire',
  'fizic',
  'digital',
  'mixt',
  'elaborare',
  'avizare_cp',
  'aprobare_ca',
  'publicare',
  'inregistrare',
  'redactare',
  'consultare_publica',
  'identificare',
  'studii',
  'cariera',
  'evaluare',
  'declaratie',
  'medical',
  'disciplina',
  'management',
  'actualizare',
  'export',
  'cerere',
  'adeverinta',
  'aviz',
  'fisa_evaluare',
  'decizie',
  'anexa',
  'emitere',
  'vechime',
  'performanta',
  'social',
  'administrativ',
  'autoevaluare',
  'impact',
  'dezvoltare',
  'incluziune',
  'evaluare_comisie',
  'validare_finala',
  'extras',
  'comunicare',
  'dispozitie',
  'analiza_juridica',
  'anonimizare',
  'aprobare_publicare',
  'validare_dosar',
  'repartizare',
  'detasare',
  'solutionare_contestatie',
  'raport_final',
  'evaluare_initiala',
  'extras_punctaj',
  'rezerva',
  'emis',
  'redistribuit',
  'propus',
  'deschis',
  'in_cercetare',
  'proiectare',
  'predare',
  'management_clasa',
  'parteneriat',
  'satisfacator',
]);

const DANGER_STATUSES = new Set([
  'blocked',
  'expired',
  'rejected',
  'inactive',
  'false',
  'planned',
  'absent_motivat',
  'absent_nemotivat',
  'respins',
  'lipsa',
  'suspendat',
  'expirat',
  'retras',
  'returned',
  'cancelled',
  'returnat',
  'contestat',
  'contested',
  'nesatisfacator',
]);

const SECONDARY_STATUSES = new Set([
  'archived',
  'waived',
]);

export function educationStatusSeverity(value: unknown): EducationStatusSeverity {
  if (typeof value === 'boolean') {
    return value ? 'success' : 'secondary';
  }

  const normalized = String(value ?? '').trim().toLowerCase();
  if (!normalized) {
    return 'secondary';
  }
  if (SUCCESS_STATUSES.has(normalized)) {
    return 'success';
  }
  if (WARN_STATUSES.has(normalized)) {
    return 'warn';
  }
  if (DANGER_STATUSES.has(normalized)) {
    return 'danger';
  }
  if (SECONDARY_STATUSES.has(normalized)) {
    return 'secondary';
  }
  return 'secondary';
}
